name: Check Uptime

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Check endpoint
        run: |
          curl --fail https://leetcode-streaker.onrender.com/api/streak/aravindhprabu2005 || exit 1
